// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ActionBtns: typeof import('./components/ActionBtns.vue')['default']
    ActionButton: typeof import('./components/ActionButton.vue')['default']
    CommentArea: typeof import('./components/CommentArea.vue')['default']
    CommentForm: typeof import('./components/CommentForm.vue')['default']
    CommentItem: typeof import('./components/CommentItem.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NPagination: typeof import('naive-ui')['NPagination']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpace: typeof import('naive-ui')['NSpace']
    Pagination: typeof import('./components/Pagination.vue')['default']
    PostList: typeof import('./components/PostList.vue')['default']
    ShowHeader: typeof import('./components/ShowHeader.vue')['default']
    Sider: typeof import('./components/Sider.vue')['default']
    Temp: typeof import('./components/temp.vue')['default']
    TempCommentForm: typeof import('./components/TempCommentForm.vue')['default']
    Test: typeof import('./components/Test.vue')['default']
    ViewMD: typeof import('./components/ViewMD.vue')['default']
  }
}

export { }
